# enabling log module
CONFIG_LOG=y
# in deffered mode
CONFIG_LOG_MODE_IMMEDIATE=y
# sets log level for modules which don't specify it explicitly to ERR
CONFIG_LOG_DEFAULT_LEVEL=1
# enable assert loging 
CONFIG_ASSERT=y
# printk messages will be threated as log with severity 0 (cannot be disabled)
CONFIG_LOG_PRINTK=y
# button and LED library
CONFIG_DK_LIBRARY=y
# add stos files
CONFIG_BT=y

CONFIG_BT_PERIPHERAL=y

CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y              
# Connection Parameters zostaną automatycznie zaktualizowane na prośbę urządzenia Peripheral
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y                    
# charakterystyka Peripheral Preferred Connection Parameters zostanie dołączona do Generic Access
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=320                           
# do wyliczenia min 400 ms
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=480                           
# do wyliczenia max 500 ms
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=200                           
# zastosować wartość 2 s.
CONFIG_BT_DEVICE_NAME="BSKS 11"                                   
# nazwa urządzenia
CONFIG_BT_DEVICE_APPEARANCE=25                                    
# pole appearance tak jak w pakiecie rozgłaszania